In [52]:
import pandas as pd
from IPython.display import display

In [53]:
movies = pd.read_csv('../archive/IMDb movies.csv')
rating = pd.read_csv('../archive/IMDb ratings.csv')
movies.head(1)

E:\Python\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,...,actors,description,avg_vote,votes,budget,usa_gross_income,worlwide_gross_income,metascore,reviews_from_users,reviews_from_critics
0,tt0000009,Miss Jerry,Miss Jerry,1894,1894-10-09,Romance,45,USA,None,Alexander Black,...,"Blanche Bayliss, William Courtenay, Chauncey D...",The adventures of a female reporter in the 1890s.,5.9,154,NaN,NaN,NaN,NaN,1.0,2.0

In [54]:
rating.head(1)

,imdb_title_id,weighted_average_vote,total_votes,mean_vote,median_vote,votes_10,votes_9,votes_8,votes_7,votes_6,...,females_30age_avg_vote,females_30age_votes,females_45age_avg_vote,females_45age_votes,top1000_voters_rating,top1000_voters_votes,us_voters_rating,us_voters_votes,non_us_voters_rating,non_us_voters_votes
0,tt0000009,5.9,154,5.9,6.0,12,4,10,43,28,...,5.7,13.0,4.5,4.0,5.7,34.0,6.4,51.0,6.0,70.0

In [55]:
mov = movies.loc[:,['imdb_title_id','title','year','date_published','genre']]
rate = rating.loc[:,['imdb_title_id', 'total_votes', 'weighted_average_vote']]
mov.head()
rate.head()

  imdb_title_id  total_votes  weighted_average_vote
0     tt0000009          154                    5.9
1     tt0000574          589                    6.1
2     tt0001892          188                    5.8
3     tt0002101          446                    5.2
4     tt0002130         2237                    7.0

In [56]:
imdb = mov.merge(how='outer', right=rate, right_on='imdb_title_id', left_on='imdb_title_id')
imdb.head(1)

,imdb_title_id,title,year,date_published,genre,total_votes,weighted_average_vote
0,tt0000009,Miss Jerry,1894,1894-10-09,Romance,154,5.9

In [57]:
netflix = pd.read_csv('../IMDB movies.csv/netflix_titles.csv')

In [58]:
netflix.head(1)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...

In [59]:
net_imdb = imdb.merge(how= 'inner', right = netflix, right_on = ['title','release_year'], left_on = ['title','year'])

In [60]:
net_imdb.head(1)

,imdb_title_id,title,year,date_published,genre,total_votes,weighted_average_vote,show_id,type,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,tt0035423,Kate & Leopold,2001,2002-03-01,"Comedy, Fantasy, Romance",77852,6.4,s3315,Movie,James Mangold,"Meg Ryan, Hugh Jackman, Liev Schreiber, Brecki...",United States,"January 1, 2020",2001,PG-13,118 min,"Comedies, Romantic Movies",A present-day woman takes responsibility for g...

# Exersice 1: Best top 5 movies in every genre

In [75]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [76]:
net_imdb.groupby('genre').size()

genre
Action                       7
Action, Adventure, Comedy    9
Action, Adventure, Crime     2
Action, Adventure, Drama     2
Action, Adventure, Family    1
                            ..
Romance, Comedy              1
Sport                        1
Thriller                     3
Thriller, Crime, Drama       1
Western                      2
Length: 154, dtype: int64

In [74]:
net_imdb['genre'].unique()

array(['Comedy, Fantasy, Romance', 'Comedy, Musical, Romance',
       'Drama, Musical, Romance', 'Crime, Drama, Romance',
       'Comedy, Drama, Musical', 'Musical, Fantasy',
       'Comedy, Musical, Drama', 'Drama, Romance',
       'Comedy, Drama, Romance', 'Action, Comedy, Crime', 'Drama, Sport',
       'Drama, Music', 'Crime, Drama', 'Drama', 'Action, Comedy, Drama',
       'Comedy, Romance', 'Action, Crime, Romance',
       'Action, Adventure, Family', 'Action, Drama', 'Comedy, Drama',
       'Romance', 'Drama, War', 'Biography, Drama, Music',
       'Action, Crime, Drama', 'Drama, Family, Musical', 'Comedy, Horror',
       'Drama, Mystery, Thriller', 'Biography, Drama, History',
       'Drama, Thriller', 'Comedy, Drama, Music',
       'Adventure, Biography, Crime', 'Animation, Adventure, Drama',
       'Action, Romance', 'Action, Adventure, Thriller', 'Comedy',
       'Action, Adventure, Fantasy', 'Comedy, Sport',
       'Comedy, Crime, Drama', 'Biography, Crime, Drama',
       'Crime, Drama, Thriller', 'Action, Adventure, Comedy',
       'Action, Thriller', 'Horror, Mystery', 'Action, Drama, Sci-Fi',
       'Action, Drama, Musical', 'Thriller, Crime, Drama',
       'Comedy, Music, Romance', 'Animation, Adventure, Family',
       'Action, Comedy, Sci-Fi', 'Comedy, Drama, Fantasy',
       'Action, Drama, Romance', 'Musical, Romance',
       'Action, Fantasy, Horror', 'Adventure, Comedy, Family',
       'Horror, Thriller', 'Horror, Romance, War',
       'Action, Comedy, Fantasy', 'Animation, Adventure, Comedy',
       'Comedy, Drama, Family', 'Drama, Family',
       'Action, Biography, Drama', 'Comedy, Sci-Fi',
       'Comedy, Romance, Drama', 'Action, Fantasy, Thriller',
       'Action, Comedy, Romance', 'Action, Adventure, Sci-Fi',
       'Comedy, Drama, Mystery', 'Family, Romance, Comedy',
       'Drama, Family, Music', 'Crime, Drama, Mystery', 'Crime, Thriller',
       'Comedy, Crime', 'Horror, Mystery, Thriller', 'Comedy, Music',
       'Action, Sci-Fi', 'Horror', 'Comedy, Family, Romance',
       'Drama, Fantasy, Mystery', 'Romance, Comedy',
       'Action, Drama, Thriller', 'Animation, Comedy, Family',
       'Biography, Drama, Sport', 'Animation, Action, Adventure',
       'Adventure, Horror, Mystery', 'Biography, Drama, Romance',
       'Drama, Romance, Thriller', 'Action, Horror, Sci-Fi',
       'Comedy, Romance, Sport', 'Action, Sci-Fi, Thriller',
       'Drama, Fantasy, History', 'Drama, Family, War',
       'Musical, Drama, Romance', 'Comedy, Mystery',
       'Crime, Horror, Mystery', 'Biography, Drama',
       'Comedy, Crime, Thriller', 'Action, Crime, Thriller',
       'Drama, History, Thriller', 'Crime, Drama, History',
       'Adventure, Family, Fantasy', 'Musical, War',
       'Biography, Comedy, Drama', 'Mystery, Thriller',
       'Comedy, Mystery, Thriller', 'Action, Crime, History',
       'Animation, Comedy, Crime', 'Action, Adventure, Mystery',
       'Comedy, Horror, Mystery', 'Drama, Fantasy', 'Adventure, Comedy',
       'Thriller', 'Action', 'Crime, Mystery, Thriller', 'Western',
       'Drama, Horror, Thriller', 'Drama, Horror, Mystery', 'Sport',
       'Action, Adventure, Horror', 'Drama, Music, Musical',
       'Biography, Comedy, Crime', 'Drama, Sci-Fi, Thriller',
       'Comedy, Drama, Thriller', 'Drama, Mystery, Sci-Fi',
       'Animation, Action, Comedy', 'Drama, Mystery',
       'Action, Adventure, Crime', 'Comedy, Drama, Horror',
       'Horror, Mystery, Romance', 'Action, Drama, Mystery',
       'Comedy, Romance, Sci-Fi', 'Comedy, Drama, Sport',
       'Mystery, Sci-Fi, Thriller', 'Comedy, Fantasy, Horror',
       'Comedy, Family', 'Action, Adventure, Drama',
       'Biography, Drama, Family', 'Adventure, Biography, Drama',
       'Comedy, Western', 'Drama, History, Musical', 'Action, Comedy',
       'Adventure, Drama, Fantasy', 'Action, Mystery, Sci-Fi',
       'Horror, Mystery, Sci-Fi', 'Drama, Thriller, War',
       'Action, Drama, War', 'Crime, Drama, Family',
       'Action, Adventure, War', 'Animation, Drama, Sci-Fi',
       'Drama, Western', 'Comedy, Family, Sci-Fi',
       'Adventure, Crime, Drama', 'Action, Drama, Horror',
       'Drama, Family, Sport', 'Adventure, Family, Sci-Fi'], dtype=object)

# Genre : Action

In [77]:
net_imdb.loc[net_imdb['genre'].str.contains('Action')].sort_values('weighted_average_vote', ascending=False).sort_values('total_votes', ascending=False).head(5)

,imdb_title_id,title,year,date_published,genre,total_votes,weighted_average_vote,show_id,type,director,cast,country,date_added,release_year,rating,duration,listed_in,description
443,tt1375666,Inception,2010,2010-09-24,"Action, Adventure, Sci-Fi",2002816,8.8,s2980,Movie,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...","United States, United Kingdom","January 1, 2020",2010,PG-13,148 min,"Action & Adventure, Sci-Fi & Fantasy, Thrillers","In this mind-bending sci-fi thriller, a man ru..."
370,tt1136608,District 9,2009,2009-09-25,"Action, Sci-Fi, Thriller",630278,7.9,s1784,Movie,Neill Blomkamp,"Sharlto Copley, Jason Cope, David James, Vanes...","South Africa, United States, New Zealand, Canada","November 4, 2019",2009,R,112 min,"Action & Adventure, International Movies, Sci-...","After years of segregation and forced labor, a..."
555,tt1825683,Black Panther,2018,2018-02-14,"Action, Adventure, Sci-Fi",597058,7.3,s960,Movie,Ryan Coogler,"Chadwick Boseman, Michael B. Jordan, Lupita Ny...",United States,"September 4, 2018",2018,PG-13,135 min,"Action & Adventure, Sci-Fi & Fantasy","T'Challa, the superpowered new leader of the h..."
290,tt0988045,Sherlock Holmes,2009,2009-12-25,"Action, Adventure, Mystery",574055,7.6,s5564,Movie,Guy Ritchie,"Robert Downey Jr., Jude Law, Rachel McAdams, M...","United States, Germany, United Kingdom, Australia","January 1, 2021",2009,PG-13,128 min,"Action & Adventure, Comedies",The game is afoot for an eccentric detective w...
183,tt0381061,Casino Royale,2006,2007-01-05,"Action, Adventure, Thriller",569968,8.0,s1235,Movie,Martin Campbell,"Daniel Craig, Judi Dench, Eva Green, Jeffrey W...","United Kingdom, Czech Republic, United States,...","August 31, 2020",2006,PG-13,145 min,Action & Adventure,Daniel Craig makes his debut as the newly mint...

## Best action movies that has total votes higher than 300,000

In [68]:
net_imdb.loc[(net_imdb['total_votes']>300000)&(net_imdb['genre'].str.contains('Action'))].sort_values('weighted_average_vote', ascending=False).head(5)

,imdb_title_id,title,year,date_published,genre,total_votes,weighted_average_vote,show_id,type,director,cast,country,date_added,release_year,rating,duration,listed_in,description
443,tt1375666,Inception,2010,2010-09-24,"Action, Adventure, Sci-Fi",2002816,8.8,s2980,Movie,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...","United States, United Kingdom","January 1, 2020",2010,PG-13,148 min,"Action & Adventure, Sci-Fi & Fantasy, Thrillers","In this mind-bending sci-fi thriller, a man ru..."
183,tt0381061,Casino Royale,2006,2007-01-05,"Action, Adventure, Thriller",569968,8.0,s1235,Movie,Martin Campbell,"Daniel Craig, Judi Dench, Eva Green, Jeffrey W...","United Kingdom, Czech Republic, United States,...","August 31, 2020",2006,PG-13,145 min,Action & Adventure,Daniel Craig makes his debut as the newly mint...
370,tt1136608,District 9,2009,2009-09-25,"Action, Sci-Fi, Thriller",630278,7.9,s1784,Movie,Neill Blomkamp,"Sharlto Copley, Jason Cope, David James, Vanes...","South Africa, United States, New Zealand, Canada","November 4, 2019",2009,R,112 min,"Action & Adventure, International Movies, Sci-...","After years of segregation and forced labor, a..."
290,tt0988045,Sherlock Holmes,2009,2009-12-25,"Action, Adventure, Mystery",574055,7.6,s5564,Movie,Guy Ritchie,"Robert Downey Jr., Jude Law, Rachel McAdams, M...","United States, Germany, United Kingdom, Australia","January 1, 2021",2009,PG-13,128 min,"Action & Adventure, Comedies",The game is afoot for an eccentric detective w...
222,tt0446029,Scott Pilgrim vs. the World,2010,2010-11-19,"Action, Comedy, Fantasy",368833,7.5,s5441,Movie,Edgar Wright,"Michael Cera, Mary Elizabeth Winstead, Kieran ...","United States, United Kingdom, Canada, Japan","September 16, 2018",2010,PG-13,112 min,"Action & Adventure, Comedies, Cult Movies",Dreamy delivery girl Ramona captures Scott Pil...

# Genre : Horror

In [78]:
net_imdb.loc[net_imdb['genre'].str.contains('Horror')].sort_values('weighted_average_vote', ascending=False).sort_values('total_votes', ascending=False).head(5)

,imdb_title_id,title,year,date_published,genre,total_votes,weighted_average_vote,show_id,type,director,cast,country,date_added,release_year,rating,duration,listed_in,description
335,tt1060277,Cloverfield,2008,2008-02-01,"Action, Adventure, Horror",367611,7.0,s1429,Movie,Matt Reeves,"Lizzy Caplan, Jessica Lucas, T.J. Miller, Mich...",United States,"January 1, 2020",2008,PG-13,85 min,"Action & Adventure, Horror Movies, Sci-Fi & Fa...",A going-away party in Manhattan is interrupted...
143,tt0298130,The Ring,2002,2003-02-21,"Horror, Mystery",315069,7.1,s6823,Movie,Gore Verbinski,"Naomi Watts, Martin Henderson, David Dorfman, ...",United States,"January 1, 2020",2002,PG-13,116 min,"Horror Movies, Thrillers",A reporter watches a video that supposedly set...
94,tt0167190,Hellboy,2004,2004-10-08,"Action, Fantasy, Horror",302680,6.8,s2692,Movie,Guillermo del Toro,"Ron Perlman, John Hurt, Selma Blair, Rupert Ev...",United States,"December 1, 2018",2004,PG-13,122 min,"Action & Adventure, Cult Movies, Sci-Fi & Fantasy",This fast-paced action flick tells the dark st...
490,tt1591095,Insidious,2010,2011-10-28,"Horror, Mystery, Thriller",271766,6.8,s3020,Movie,James Wan,"Patrick Wilson, Rose Byrne, Lin Shaye, Ty Simp...","United States, Canada, United Kingdom","May 9, 2019",2010,PG-13,103 min,"Horror Movies, Thrillers","Hoping to leave their haunted house behind, a ..."
103,tt0195714,Final Destination,2000,2000-08-25,"Horror, Thriller",224856,6.7,s2164,Movie,James Wong,"Devon Sawa, Ali Larter, Kerr Smith, Kristen Cl...",United States,"January 1, 2020",2000,R,98 min,"Cult Movies, Horror Movies, Thrillers",After narrowly avoiding a fatal plane explosio...

## Best horror movies that has total votes higher than 300,000

In [83]:
net_imdb.loc[(net_imdb['total_votes']>300000)&(net_imdb['genre'].str.contains('Horror'))].sort_values('weighted_average_vote', ascending=False).head()

,imdb_title_id,title,year,date_published,genre,total_votes,weighted_average_vote,show_id,type,director,cast,country,date_added,release_year,rating,duration,listed_in,description
143,tt0298130,The Ring,2002,2003-02-21,"Horror, Mystery",315069,7.1,s6823,Movie,Gore Verbinski,"Naomi Watts, Martin Henderson, David Dorfman, ...",United States,"January 1, 2020",2002,PG-13,116 min,"Horror Movies, Thrillers",A reporter watches a video that supposedly set...
335,tt1060277,Cloverfield,2008,2008-02-01,"Action, Adventure, Horror",367611,7.0,s1429,Movie,Matt Reeves,"Lizzy Caplan, Jessica Lucas, T.J. Miller, Mich...",United States,"January 1, 2020",2008,PG-13,85 min,"Action & Adventure, Horror Movies, Sci-Fi & Fa...",A going-away party in Manhattan is interrupted...
94,tt0167190,Hellboy,2004,2004-10-08,"Action, Fantasy, Horror",302680,6.8,s2692,Movie,Guillermo del Toro,"Ron Perlman, John Hurt, Selma Blair, Rupert Ev...",United States,"December 1, 2018",2004,PG-13,122 min,"Action & Adventure, Cult Movies, Sci-Fi & Fantasy",This fast-paced action flick tells the dark st...

# Science Fiction

In [86]:
net_imdb.loc[net_imdb['genre'].str.contains('Sci-Fi')].sort_values('weighted_average_vote', ascending=False).sort_values('total_votes', ascending=False).head(5)

,imdb_title_id,title,year,date_published,genre,total_votes,weighted_average_vote,show_id,type,director,cast,country,date_added,release_year,rating,duration,listed_in,description
443,tt1375666,Inception,2010,2010-09-24,"Action, Adventure, Sci-Fi",2002816,8.8,s2980,Movie,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...","United States, United Kingdom","January 1, 2020",2010,PG-13,148 min,"Action & Adventure, Sci-Fi & Fantasy, Thrillers","In this mind-bending sci-fi thriller, a man ru..."
370,tt1136608,District 9,2009,2009-09-25,"Action, Sci-Fi, Thriller",630278,7.9,s1784,Movie,Neill Blomkamp,"Sharlto Copley, Jason Cope, David James, Vanes...","South Africa, United States, New Zealand, Canada","November 4, 2019",2009,R,112 min,"Action & Adventure, International Movies, Sci-...","After years of segregation and forced labor, a..."
555,tt1825683,Black Panther,2018,2018-02-14,"Action, Adventure, Sci-Fi",597058,7.3,s960,Movie,Ryan Coogler,"Chadwick Boseman, Michael B. Jordan, Lupita Ny...",United States,"September 4, 2018",2018,PG-13,135 min,"Action & Adventure, Sci-Fi & Fantasy","T'Challa, the superpowered new leader of the h..."
201,tt0413300,Spider-Man 3,2007,2007-05-01,"Action, Adventure, Sci-Fi",489497,6.2,s5754,Movie,Sam Raimi,"Tobey Maguire, Kirsten Dunst, James Franco, Th...",United States,"November 1, 2019",2007,PG-13,139 min,"Action & Adventure, Sci-Fi & Fantasy",The seemingly invincible Spider-Man goes up ag...
216,tt0438488,Terminator Salvation,2009,2009-06-05,"Action, Adventure, Sci-Fi",339181,6.5,s6027,Movie,McG,"Christian Bale, Sam Worthington, Moon Bloodgoo...","United States, Germany, United Kingdom, Italy","January 1, 2020",2009,PG-13,115 min,"Action & Adventure, Sci-Fi & Fantasy","All grown up in post-apocalyptic 2018, John Co..."

## Best Science Fiction movies that has total votes higher than 300,000

In [87]:
net_imdb.loc[(net_imdb['total_votes']>300000)&(net_imdb['genre'].str.contains('Sci-Fi'))].sort_values('weighted_average_vote', ascending=False).head()

,imdb_title_id,title,year,date_published,genre,total_votes,weighted_average_vote,show_id,type,director,cast,country,date_added,release_year,rating,duration,listed_in,description
443,tt1375666,Inception,2010,2010-09-24,"Action, Adventure, Sci-Fi",2002816,8.8,s2980,Movie,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...","United States, United Kingdom","January 1, 2020",2010,PG-13,148 min,"Action & Adventure, Sci-Fi & Fantasy, Thrillers","In this mind-bending sci-fi thriller, a man ru..."
370,tt1136608,District 9,2009,2009-09-25,"Action, Sci-Fi, Thriller",630278,7.9,s1784,Movie,Neill Blomkamp,"Sharlto Copley, Jason Cope, David James, Vanes...","South Africa, United States, New Zealand, Canada","November 4, 2019",2009,R,112 min,"Action & Adventure, International Movies, Sci-...","After years of segregation and forced labor, a..."
384,tt1182345,Moon,2009,2009-12-04,"Drama, Mystery, Sci-Fi",329812,7.9,s4222,Movie,Duncan Jones,"Sam Rockwell, Kevin Spacey, Dominique McElligo...","United Kingdom, United States","January 1, 2020",2009,R,97 min,"Dramas, Independent Movies, Sci-Fi & Fantasy",As he nears the end of a lonely three-year sti...
118,tt0238380,Equilibrium,2002,2003-07-11,"Action, Drama, Sci-Fi",308150,7.4,s2019,Movie,Kurt Wimmer,"Christian Bale, Emily Watson, Taye Diggs, Angu...",United States,"June 8, 2019",2002,R,107 min,"Action & Adventure, Dramas, Sci-Fi & Fantasy","In a dystopian future, a totalitarian regime m..."
555,tt1825683,Black Panther,2018,2018-02-14,"Action, Adventure, Sci-Fi",597058,7.3,s960,Movie,Ryan Coogler,"Chadwick Boseman, Michael B. Jordan, Lupita Ny...",United States,"September 4, 2018",2018,PG-13,135 min,"Action & Adventure, Sci-Fi & Fantasy","T'Challa, the superpowered new leader of the h..."

# Most popular genre

In [90]:
import seaborn as sns

In [93]:
net_imdb.head(2)

,imdb_title_id,title,year,date_published,genre,total_votes,weighted_average_vote,show_id,type,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,tt0035423,Kate & Leopold,2001,2002-03-01,"Comedy, Fantasy, Romance",77852,6.4,s3315,Movie,James Mangold,"Meg Ryan, Hugh Jackman, Liev Schreiber, Brecki...",United States,"January 1, 2020",2001,PG-13,118 min,"Comedies, Romantic Movies",A present-day woman takes responsibility for g...
1,tt0051658,Gigi,1958,1959-04-09,"Comedy, Musical, Romance",19203,6.7,s2411,Movie,"Vincente Minnelli, Charles Walters","Leslie Caron, Maurice Chevalier, Louis Jourdan...",United States,"November 1, 2019",1958,G,115 min,"Classic Movies, Comedies, Music & Musicals",Gigi's an avant-garde French waif being groome...

In [100]:
net_imdb.groupby('director').size().sort_values(ascending=False)

director
Rajkumar Santoshi                  6
David Dhawan                       6
Farhan Akhtar                      5
Anees Bazmee                       5
Clint Eastwood                     4
                                  ..
Joachim Rønning, Espen Sandberg    1
Jesse V. Johnson                   1
Jeremy Saulnier                    1
Jennifer Lynch                     1
Mark Steven Johnson                1
Length: 487, dtype: int64

In [110]:
high_rated_mov = net_imdb.loc[net_imdb['weighted_average_vote']> 8].sort_values('weighted_average_vote',ascending=False)
high_rated_mov.head(5)

,imdb_title_id,title,year,date_published,genre,total_votes,weighted_average_vote,show_id,type,director,cast,country,date_added,release_year,rating,duration,listed_in,description
45,tt0108052,Schindler's List,1993,1994-03-11,"Biography, Drama, History",1183248,8.9,s5431,Movie,Steven Spielberg,"Liam Neeson, Ben Kingsley, Ralph Fiennes, Caro...",United States,"April 1, 2018",1993,R,195 min,"Classic Movies, Dramas",Oskar Schindler becomes an unlikely humanitari...
49,tt0110912,Pulp Fiction,1994,1994-10-28,"Crime, Drama",1780147,8.9,s5003,Movie,Quentin Tarantino,"John Travolta, Samuel L. Jackson, Uma Thurman,...",United States,"January 1, 2019",1994,R,154 min,"Classic Movies, Cult Movies, Dramas",This stylized crime caper weaves together stor...
443,tt1375666,Inception,2010,2010-09-24,"Action, Adventure, Sci-Fi",2002816,8.8,s2980,Movie,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...","United States, United Kingdom","January 1, 2020",2010,PG-13,148 min,"Action & Adventure, Sci-Fi & Fantasy, Thrillers","In this mind-bending sci-fi thriller, a man ru..."
151,tt0317248,City of God,2002,2003-05-09,"Crime, Drama",685856,8.6,s1401,Movie,"Fernando Meirelles, Katia Lund","Alexandre Rodrigues, Leandro Firmino, Phellipe...","Brazil, France, Germany","January 1, 2020",2002,R,130 min,"Dramas, Independent Movies, International Movies","Growing up in a Rio de Janeiro slum, Rocket is..."
18,tt0079221,Gol Maal,1979,1979-04-20,"Comedy, Romance",17381,8.6,s2464,Movie,Hrishikesh Mukherjee,"Amol Palekar, Bindiya Goswami, Deven Verma, Ut...",India,"December 31, 2019",1979,TV-PG,137 min,"Classic Movies, Comedies, International Movies",When circumstances at work compel Ram to prete...

In [117]:
high_rated_mov.groupby('director').size().sort_values(ascending= False)

director
Rajkumar Santoshi                 2
Hrishikesh Mukherjee              2
Quentin Tarantino                 2
Anubhav Sinha                     1
Oliver Stone                      1
Vikramaditya Motwane              1
Tony Kaye                         1
Sujoy Ghosh                       1
Steven Spielberg                  1
Shekhar Kapur                     1
Sam Mendes                        1
Rakeysh Omprakash Mehra           1
Rajkumar Hirani                   1
Parthiban                         1
Neeraj Pandey                     1
Anurag Basu                       1
Marwan Hamed                      1
Martin Scorsese                   1
John G. Avildsen                  1
Gulzar                            1
Fernando Meirelles, Katia Lund    1
Farhan Akhtar                     1
Danny Boyle                       1
Clint Eastwood                    1
Christopher Nolan                 1
Balu Mahendra                     1
Anurag Kashyap                    1
Zoya Akhtar                       1
dtype: int64

# Popular movies from country

In [118]:
high_rated_mov.groupby('country').size().sort_values(ascending= False)

country
India                            18
United States                     7
United States, United Kingdom     2
Brazil, France, Germany           1
Egypt                             1
Germany, United States            1
United Kingdom                    1
dtype: int64